spring:
  datasource:
    driverClassName: org.h2.Driver
    password: test
    url: jdbc:h2:mem:test
    username: test
  sql:
    init:
      data-locations: classpath:db/data.sql
      platform: h2
      schema-locations: classpath:db/schema.sql
